name: silhouette_quiz
description: "Silhouette quiz for kids."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # ローカライズ（GlobalMaterialLocalizations など）
  flutter_localizations:
    sdk: flutter

  # iOS っぽいアイコン
  cupertino_icons: ^1.0.8

  # ★ 追加：カメラ・ギャラリーから画像を取る
  image_picker: ^1.0.7
  google_fonts: ^6.1.0

  # Hive
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2

  # Image processing
  image: ^4.1.3

  # ML Kit for subject segmentation
  google_mlkit_subject_segmentation: ^0.0.2

dev_dependencies:
  hive_generator: ^2.0.0
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/backgrounds/
    - assets/images/quiz/home/
    - assets/images/character/

    - assets/images/button/
    - assets/images/conveyor.png
    - assets/images/conveyor_y.png
    - assets/images/box.png
    - assets/images/piping.png
